Repository ntrappe/cse112-s22-group2, pull requests merged in 2022-06, with the labels that each got.

#35 notes hooked up to storage
  source/backend/storage.js
  source/components/control/control.js
  source/components/daily-log-preview/daily-log-preview.js
  source/components/daily-log/daily-log.js
  source/components/daily-log/notes-script.js
  source/index.html
  source/styles/daily-log.css
Labels: PR: Needs Review

#39 grey out/disable inbox btns
  source/components/control/control.js
  source/styles/inbox.css
Labels: enhancement, PR: Needs Review

#42 fixed auto scrolling issue
  source/components/daily-log/daily-log.js
  source/components/daily-log/notes-script.js
  source/styles/daily-log-preview.css
  source/styles/daily-log.css
Labels: PR: Needs Review

#45 Tracker control
  .github/workflows/Linting.yml
  .stylelintrc.json
  source/backend/storage.js
  source/components/control/control.js
  source/components/daily-log/daily-log.js
  source/components/daily-log/notes-script.js
  source/components/tracker-modal/emoji-picker.js
  source/components/tracker-modal/tracker-modal.js
  source/index.html
  source/styles/daily-log.css
  source/styles/emoji-picker.css
  source/styles/home-screen.css
  source/styles/tracker-home.css
  source/styles/tracker-modal.css
  source/trackers.html
  testing/cypress/control-test.js
  testing/cypress/home-screen-test.js
  testing/cypress/inbox-page-test.js
  testing/cypress/inbox-screen-test.js
  testing/cypress/maggie_test.js
  testing/jest/storage-test.js
Labels: PR: Needs Review

#46 fix lock
  .github/workflows/Linting.yml
  package-lock.json
Labels: bug

#47 save emoji picker locally
  node_modules/emoji-picker-element/CHANGELOG.md
  node_modules/emoji-picker-element/LICENSE
  node_modules/emoji-picker-element/README.md
  node_modules/emoji-picker-element/custom-elements.json
  node_modules/emoji-picker-element/database.d.ts
  node_modules/emoji-picker-element/database.js
  node_modules/emoji-picker-element/database.js.map
  node_modules/emoji-picker-element/i18n/ar.d.ts
  node_modules/emoji-picker-element/i18n/ar.js
  node_modules/emoji-picker-element/i18n/de.d.ts
  node_modules/emoji-picker-element/i18n/de.js
  node_modules/emoji-picker-element/i18n/en.d.ts
  node_modules/emoji-picker-element/i18n/en.js
  node_modules/emoji-picker-element/i18n/es.d.ts
  node_modules/emoji-picker-element/i18n/es.js
  node_modules/emoji-picker-element/i18n/fr.d.ts
  node_modules/emoji-picker-element/i18n/fr.js
  node_modules/emoji-picker-element/i18n/ms_MY.d.ts
  node_modules/emoji-picker-element/i18n/ms_MY.js
  node_modules/emoji-picker-element/i18n/nl.d.ts
  node_modules/emoji-picker-element/i18n/nl.js
  node_modules/emoji-picker-element/i18n/pt_BR.d.ts
  node_modules/emoji-picker-element/i18n/pt_BR.js
  node_modules/emoji-picker-element/i18n/pt_PT.d.ts
  node_modules/emoji-picker-element/i18n/pt_PT.js
  node_modules/emoji-picker-element/i18n/tr.d.ts
  node_modules/emoji-picker-element/i18n/tr.js
  node_modules/emoji-picker-element/index.d.ts
  node_modules/emoji-picker-element/index.js
  node_modules/emoji-picker-element/package.json
  node_modules/emoji-picker-element/picker.d.ts
  node_modules/emoji-picker-element/picker.js
  node_modules/emoji-picker-element/picker.js.map
  node_modules/emoji-picker-element/shared.d.ts
  node_modules/emoji-picker-element/svelte.js
  node_modules/emoji-picker-element/svelte.js.map
  node_modules/emoji-picker-element/trimEmojiData.cjs
  node_modules/emoji-picker-element/trimEmojiData.cjs.map
  node_modules/emoji-picker-element/trimEmojiData.d.ts
  node_modules/emoji-picker-element/trimEmojiData.js
  node_modules/emoji-picker-element/trimEmojiData.js.map
Labels: bug
