Repository ntrappe/cse112-s22-group2, pull requests merged in 2022-05, with the labels that each got.

#4 Docs workflow
  .github/workflows/JSDocs.yml
Labels: CI/CD, PR: Ready to Merge

#6 HTML linter addition
  .github/workflows/Linting.yml
  .htmlhintrc
  html-linter-config.json
  index.html
  package.json
Labels: PR: Ready to Merge

#5 Test workflow
  .github/workflows/Testing.yml
  cypress.json
  jest.config.js
  package.json
Labels: CI/CD, PR: Needs Review

#11 Maggie initital testing
  .gitignore
  testing/cypress/maggie_test.js
Labels: PR: Ready to Merge

#17 home screen mobile up (button icon not done nor is it clickable)
  .stylelintrc.json
  source/index.html
  source/styles/home-screen.css
Labels: PR: Ready to Merge, design, MVP

#18 added home screen UI tests
  testing/cypress/frontend_test.js
  testing/cypress/home-screen-test.js
Labels: PR: Needs Review, testing

#21 Daily log preview
  source/add-component.js
  source/components/daily-log-preview/daily-log-preview.js
  source/icons/arrow-icon.png
  source/icons/journal-icon-off.png
  source/icons/journal-icon-on.png
  source/icons/journal_icon.svg
  source/icons/notes-icon-off.png
  source/icons/notes-icon-on.png
  source/icons/notes_icon.svg
  source/icons/tracker-icon-off.png
  source/icons/tracker-icon-on.png
  source/icons/tracker_icon.svg
  source/inbox.html
  source/index.html
  source/styles/daily-log-preview.css
  source/styles/home-screen.css
  testing/cypress/home-screen-test.js
Labels: PR: Ready to Merge

#22 Daily log component
  .eslintrc.json
  source/components/daily-log/daily-log.js
  source/styles/daily-log.css
  testing/cypress/daily-log-test.js
Labels: PR: Ready to Merge

#19 Frontend inbox features
  source/add-component.js
  source/components/popup-modal/popup-modal.js
  source/icons/new-log-icon.png
  source/inbox.html
  source/index.js
  source/styles/daily-log-preview.css
  source/styles/home-screen.css
  source/styles/inbox.css
  source/styles/popup-modal.css
  testing/cypress/baitong_test.js
Labels: PR: Ready to Merge

#30 Frontend inbox feature tests
  source/components/popup-modal/popup-modal.js
  source/index.js
  testing/cypress/baitong_test.js
  testing/cypress/inbox-page-test.js
Labels: PR: Needs Review, testing

#31 Control
  .babelrc
  .eslintrc.json
  source/add-component.js
  source/backend/storage.js
  source/components/control/control-helpers.js
  source/components/control/control.js
  source/components/control/inbox-helper.js
  source/components/daily-log-preview/daily-log-preview.js
  source/components/daily-log/daily-log.js
  source/components/popup-modal/popup-modal.js
  source/inbox.html
  source/styles/daily-log-preview.css
  source/styles/daily-log.css
  testing/cypress/control-test.js
  testing/cypress/frontend_test.js
  testing/cypress/inbox-page-test.js
  testing/jest/backend_tests.js
  testing/jest/storage-test.js
Labels: PR: Needs Review
